### ISSUE TITLE
mybatisplus-plus 1.5.0的demo启动报错

### ISSUE THREAD

**Issue by YahvehW** [jeffreyning/mybatisplus-plus#1]
报错信息：
Error creating bean with name 'com.github.jeffreyning.mybatisplus.conf.PlusConfig': Invocation of init method failed; nested exception is java.lang.NoSuchFieldException: modifiers
![image](https://user-images.githubusercontent.com/37897711/119926397-eb1f3000-bfa9-11eb-8f7b-f52e3f9bc973.png)

**Comment by jeffreyning** [comment]
具体是哪个test方法报错，testUpdateBatchByMultiIdService、testSaveOrUpdateBatchByMultiIdService等方法执行均没报错。

**Comment by weiqiuyun1112** [comment]
您好请问您解决了吗？我今天也遇到了相同的问题
