### ISSUE TITLE
mpp.entityBasePath is null skip scan result map

### ISSUE THREAD

**Issue by shpilu** [jeffreyning/mybatisplus-plus#11]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/14285295/204955226-f74f8fe0-506c-4e27-af4f-47732715accc.png">

**Comment by shpilu** [comment]
使用mpp时启动报这个错误: 2022-12-01 10:52:54.119 ERROR 73180 --- [           main] c.g.j.mybatisplus.conf.PlusConfig        : mpp.entityBasePath is null skip scan result map
版本信息：
    
    <dependency>
      <groupId>com.baomidou</groupId>
      <artifactId>mybatis-plus-boot-starter</artifactId>
      <version>3.4.3.2</version>
    </dependency>
    <dependency>
      <groupId>com.github.jeffreyning</groupId>
      <artifactId>mybatisplus-plus</artifactId>
      <version>1.7.0-RELEASE</version>
    </dependency>
    <dependency>
      <groupId>com.baomidou</groupId>
      <artifactId>mybatis-plus-generator</artifactId>
      <version>3.4.1</version>
    </dependency>

**Comment by jeffreyning** [comment]
启动时日志中有mpp.entityBasePath is null skip scan result map 只是个提示不影响，不想看到提示，mpp.entityBasePath可以配置到entity的包如entityBasePath: com.github.jeffreyning.mybatisplus.demo.entity； 如果xml中有resultMap="scan.mybatis-plus_xxx"才需要配置mpp.entityBasePath

**Comment by jeffreyning** [comment]
在mpp1.7.2中已经将此报错降级为warn显示
