### ISSUE TITLE
可否升级一下以适配mybatis-plus3.5.3? 

### ISSUE THREAD

**Issue by hbx2052** [jeffreyning/mybatisplus-plus#13]
AbstractMethod移除了无参构造器，自定义的MultiId方法目前都报错了

**Comment by SellerJoke** [comment]
提供一个临时解决方案。
在自己的项目中分别覆盖mybatisplus-plus包中的SelectByMultiIdMethod、UpdateByMultiIdMethod、DeleteByMultiId、MppSqlInjector等类。
SelectByMultiIdMethod、UpdateByMultiIdMethod、DeleteByMultiId三个类都继承自AbstractMethod抽象类，而AbstractMethod只有一个有一个String参数的构造器，所以在这三个类中自己写有一个String参数的构造器，在这些构造器中，只调用父类的有参构造器，不做其他操作。
MppSqlInjector类的getMethodList方法中原先是调用SelectByMultiIdMethod、UpdateByMultiIdMethod、DeleteByMultiId类的无参构造器生成实例对象，现在只能调用它们的有参构造器生成实例对象。这些有参构造器的参数就是它们对应类名去掉末尾的Method的小驼峰形式。例如实例化SelectByMultiIdMethod类，可以这样写：new SelectByMultiIdMethod("selectByMultiId")。

**Comment by jeffreyning** [comment]
发布了mybatisplus-plus1.7.3可以与mybatisplus3.5.1+兼容（已经测试到mybatisplus3.5.3.1 20230129）
