### ISSUE TITLE
兼容dynamic-datasource-spring-boot-starter时动态切换数据源失败

### ISSUE THREAD

**Issue by ixiaohaii** [jeffreyning/mybatisplus-plus#15]

**Comment by jeffreyning** [comment]
用mpp1.7.1和dynamic-datasource-spring-boot-starter3.5做过测试没有问题，可以加qq群1028241274，下载demo

**Comment by ixiaohaii** [comment]
成功了，之前@DS注解放在mapper层，移到service实现类就可以了
