### ISSUE TITLE
主键MppMultiId不可继承

### ISSUE THREAD

**Issue by 2HENGYUN** [jeffreyning/mybatisplus-plus#2]
## 版本号
1.5.1-RELEASE
## 描述
在父类中定义主键字段并使用MppMultiId，子类的saveOrUpdateByMultiId()找不到主键，抛出异常
* com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: entity {} not contain MppMultiId anno 
## 疑问
看了saveOrUpdateByMultiId()方法的源码
感觉是遍历字段的时候(com.github.jeffreyning.mybatisplus.service.MppServiceImpl.java:38)
是手动反射的目标的字段(com.github.jeffreyning.mybatisplus.service.MppServiceImpl.java:36)
* 而getDeclaredFields()方法获取不到父类的字段
* 为啥不遍历mybatis-plus生成的表信息缓存呢(com.github.jeffreyning.mybatisplus.service.MppServiceImpl.java:35)

**Comment by SellerJoke** [comment]
赞同啊，我也想要这个功能。
MyBatis Plus是支持实体类继承的，可以读取到祖先类中的字段，但是MyBatisPlus Plus就忽略了祖先类中的@MppMultiId注解。

**Comment by jeffreyning** [comment]
已提交mpp1.7.1版本支持继承多主键entity
