### ISSUE TITLE
能否兼容MyBatis Plus 3.4.3.2及以上版本？

### ISSUE THREAD

**Issue by SellerJoke** [jeffreyning/mybatisplus-plus#4]
我是个更新怪，什么软件都喜欢用最新版的。更新后发现MyBatisPlus Plus不支持MyBatis Plus 3.4.3.2及以上版本，使用MyBatisPlus Plus的CRUD方法会抛出“BindingException: Invalid bound statement (not found)”异常，也许修改了什么设置就能兼容了吧。虽然此项目主页已经说明了最高兼容MyBatis 3.4.2，但是还是希望能尽量兼容。

**Comment by jeffreyning** [comment]
1.6.0兼容MyBatis Plus 3.4.3.2及以上版本
