### ISSUE TITLE
自定义SQL可否支持字段填充？

### ISSUE THREAD

**Issue by mancong** [jeffreyning/mybatisplus-plus#6]
此篇文章说道了改问题。[mybatis plus自动填充功能使用注意事项](https://www.cnblogs.com/siroinfo/p/13095637.html ) ，我所遇到的问题：如果使用手写SQL方式批量INSERT 则无法生效。但是在调试时候：二次手动执行则可以填充生效，老哥有解决方案或思路吗？

**Comment by jeffreyning** [comment]
这里沿用的mp原生的功能
