### ISSUE TITLE
mybatisplus-plus-1.5.1  modifiers

### ISSUE THREAD

**Issue by petma** [jeffreyning/mybatisplus-plus#7]
LambdaUtil 类，setValue方法，这个modifiers是用来做啥的？启动时提示找不到这个field
public static void setValue(Class cls, String fileName, Object value)
            throws NoSuchFieldException, SecurityException, IllegalArgumentException, IllegalAccessException {
        Field field = cls.getDeclaredField(fileName);
        field.setAccessible(true);
        Field modifiersField = Field.class.getDeclaredField("modifiers");
        modifiersField.setAccessible(true);
        modifiersField.setInt(field, field.getModifiers() & ~Modifier.FINAL);
        field.set(cls, value);
    }

**Comment by petma** [comment]
对了，我也是jdk11

**Comment by jeffreyning** [comment]
未能复现此问题
mybatisplus-plus：1.6.0-RELEASE
mybatis-plus-boot-starter：3.4.3.4
将plus-demo打成jar包用java -jar执行，在windows下和centos下均正常启动
使用的jdk为1.8
使用jdk11在windows中执行也没有报错

建议把plus-demo打包看是否启动报错

**Comment by petma** [comment]
> 未能复现此问题 mybatisplus-plus：1.6.0-RELEASE mybatis-plus-boot-starter：3.4.3.4 将plus-demo打成jar包用java -jar执行，在windows下和centos下均正常启动 使用的jdk为1.8 使用jdk11在windows中执行也没有报错
> 
> 建议把plus-demo打包看是否启动报错

用plus-demo 1.5.1版，一样报错

**Comment by petma** [comment]
1.6.0版本一样的报错。
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.github.jeffreyning.mybatisplus.conf.PlusConfig': Invocation of init method failed; nested exception is java.lang.NoSuchFieldException: modifiers

**Comment by jeffreyning** [comment]
下周我把这功能取消了

**Comment by jeffreyning** [comment]
mpp 1.7.0版本已经提交，删除了自定义ognl根路径功能，应该可以兼容jdk11，请试试。

**Comment by petma** [comment]
升级到1.7.0之后，报 Invalid bound statement (not found): XXXMapper.selectByMultiId  这个错
  <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.4.1</version>
        </dependency>

**Comment by petma** [comment]
有在application处加注解
@EnableMPP

**Comment by jeffreyning** [comment]
mpp1.7要使用mybatisplus3.4.3.2+
