### ISSUE TITLE
@MppMultiId 注释的属性名不能叫id，否则会报 not found column for 'id' 的RuntimeException

### ISSUE THREAD

**Issue by zll11111** [jeffreyning/mybatisplus-plus#8]

**Comment by zll11111** [comment]
![IMG_20220321_105511](https://user-images.githubusercontent.com/3368608/159199497-f52e9dd9-6b8d-44ae-aa9f-1c161c5d5724.jpg)
mybatis-plus的锅，所有叫id的属性都自动注册为主键，可以关闭问题了。

**Comment by jeffreyning** [comment]
多谢提醒
