### ISSUE TITLE
使用复合主键saveOrUpdateBatch报Invalid bound statement (not found)

### ISSUE THREAD

**Issue by davon-noidea** [jeffreyning/mybatisplus-plus#9]
版本：
mybatis-plus-boot-starter ： 3.3.2
mybatisplus-plus： 1.7.0-RELEASE

报错内容：
Caused by: org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): cn.powersi.phys.dao.TbJyzbgDao.selectByMultiId

我的配置：
已在启动类添加@EnableMPP注解
实体类对应的复合主键上都添加了@MppMultiId @TableField 注解
mapper、service和serviceImpl都已继承相应的类

已排除自定义MetaObjectHandler和sqlSessionFactory导致的原因，求赐教[抱拳]

**Comment by jeffreyning** [comment]
mybatisplus的版本是？版本太低也不行。mybatisplus-plus1.5.0兼容mybatisplus3.3.1(mybatis3.5.3)到最新版mybatisplus3.4.2(mybatis3.5.6) mybatisplus-plus1.5.1与最高到mybatisplus3.4.3.1兼容 （mybatisplus-plus1.5.1与mybatisplus3.4.3不兼容，mybatisplus3.4.3自身有bug无法使用，报sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class） （mybatisplus-plus1.5.1与mybatisplus3.4.3.2不兼容，报org.apache.ibatis.binding.BindingException: Invalid bound statement (not found)） mybatisplus-plus1.6.0与mybatisplus3.4.3.2+兼容（已经测试到mybatisplus3.4.3.4） mybatisplus-plus1.7.0兼容jdk11(删除了自定义ognl根路径功能)

**Comment by davon-noidea** [comment]
谢谢你的解答，项目使用的mybatis-plus版本是3.3.2，现在我把mybatisplus-plus的版本从1.7.0-RELEASE 降到1.5.1.RELEASE 已经解决该报错的问题
